// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx1rNj_UFkh_eYQqBRCAgHGeT8kzxnvdg',
    appId: '1:386297832036:web:18b7051696e882d8ed3571',
    messagingSenderId: '386297832036',
    projectId: 'fitnessplus-a318f',
    authDomain: 'fitnessplus-a318f.firebaseapp.com',
    storageBucket: 'fitnessplus-a318f.appspot.com',
    measurementId: 'G-87MEVXY1H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQECrmZXgipogrcyiJBJ-Vn0ZwFGf4h0',
    appId: '1:386297832036:android:552a530a884ef7c5ed3571',
    messagingSenderId: '386297832036',
    projectId: 'fitnessplus-a318f',
    storageBucket: 'fitnessplus-a318f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMSlrhdaFDuoOeMUKCy1VtE_OImG27JU',
    appId: '1:386297832036:ios:9e8e205fcd4e6074ed3571',
    messagingSenderId: '386297832036',
    projectId: 'fitnessplus-a318f',
    storageBucket: 'fitnessplus-a318f.appspot.com',
    iosBundleId: 'com.pi.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMSlrhdaFDuoOeMUKCy1VtE_OImG27JU',
    appId: '1:386297832036:ios:01120050527ad901ed3571',
    messagingSenderId: '386297832036',
    projectId: 'fitnessplus-a318f',
    storageBucket: 'fitnessplus-a318f.appspot.com',
    iosBundleId: 'com.pi.fitnessWorkoutAppFlutter3Ui.RunnerTests',
  );
}
